{
 "title": "JWT Pizza Service",
 "tags": [
  "jwt-pizza-service",
  "deliverable8"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "2. Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active users"
    }
   ]
  },
  {
   "title": "3. Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqm" } },
   "targets": [
    {
     "expr": "rate(auth_success_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_failure_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "1. HTTP requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqm" } },
   "targets": [
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[1m])) * 60",
     "legendFormat": "all"
    },
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\", endpoint=~\"GET .*\"}[1m])) * 60",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\", endpoint=~\"PUT .*\"}[1m])) * 60",
     "legendFormat": "put"
    },
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\", endpoint=~\"POST .*\"}[1m])) * 60",
     "legendFormat": "post"
    },
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\", endpoint=~\"DELETE .*\"}[1m])) * 60",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(request_duration_sum_ms_milliseconds_total{source=\"jwt-pizza-service\"}[1m]) / (rate(request_duration_count_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(pizza_failures_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Purchase failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_revenue_total{source=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pizza_creation_latency_ms_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza latency"
    }
   ]
  }
 ]
}