#!/usr/bin/env bash
#
# Drive traffic against JWT Pizza Service so Grafana logs + metrics panels fill in.
# Generates varied HTTP logs (richer reqBody/resBody) like the course “Awesome Dashboard”.
# Based on: instruction/simulatingTraffic/simulatingTraffic.md
#
# Requirements: bash, curl, jq  →  brew install jq
#
# HOW TO RUN
#   cd /path/to/jwt-pizza-service
#   chmod +x scripts/simulate-dashboard-traffic.sh    # first time only
#   ./scripts/simulate-dashboard-traffic.sh
#
# Default URL is https://pizza-service.saamn.dev
#   ./scripts/simulate-dashboard-traffic.sh http://localhost:3000
#
# Stop: Ctrl+C in this terminal (stops all background loops)
#
# Note: Occasional POST /api/auth creates unique “traffic_*” users in your DB (low rate).
#

set -euo pipefail

HOST="${1:-https://pizza-service.saamn.dev}"
echo "==> Target: $HOST"
echo "==> Press Ctrl+C to stop all loops"
echo ""

if ! command -v jq &>/dev/null; then
  echo "Error: jq is required. Install with: brew install jq"
  exit 1
fi

PIDS=()

cleanup() {
  echo ""
  echo "==> Stopping background loops..."
  for pid in "${PIDS[@]}"; do
    kill "$pid" 2>/dev/null || true
  done
  exit 0
}
trap cleanup SIGINT SIGTERM

start() {
  "$@" &
  PIDS+=("$!")
}

# --- Light reads: welcome + docs (empty req → JSON res with version/endpoints) ---
start bash -c 'while true; do curl -s -o /dev/null "$0/"; sleep 12; done' "$HOST"
start bash -c 'while true; do curl -s -o /dev/null "$0/api/docs"; sleep 20; done' "$HOST"

# --- Menu reads (two rates) ---
start bash -c 'while true; do curl -s -o /dev/null "$0/api/order/menu"; sleep 3; done' "$HOST"
start bash -c 'while true; do curl -s -o /dev/null "$0/api/order/menu"; sleep 1; done' "$HOST"

# --- Public franchise list (GET, empty body, JSON list in res) ---
start bash -c 'while true; do
  curl -s -o /dev/null "$0/api/franchise?page=0&limit=5&name=*"
  sleep 18
done' "$HOST"

# --- Bad login (exceptions) — slower so HTTP rows are not drowned out ---
start bash -c 'while true; do
  curl -s -o /dev/null -X PUT "$0/api/auth" \
    -d "{\"email\":\"unknown@jwt.com\",\"password\":\"not-the-secret\"}" \
    -H "Content-Type: application/json"
  sleep 22
done' "$HOST"

# --- Register with unique user — fat reqBody (name/email/password), fat res (user + token) ---
start bash -c 'while true; do
  n=$(date +%s%N)
  curl -s -o /dev/null -X POST "$0/api/auth" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"Dashboard Traffic Bot ${n}\",\"email\":\"traffic_${n}@jwt.com\",\"password\":\"diner\"}"
  sleep 90
done' "$HOST"

# --- Admin: login → add menu item (large JSON body) → list users ---
start bash -c 'while true; do
  r=$(curl -s -X PUT "$0/api/auth" \
    -d "{\"email\":\"a@jwt.com\",\"password\":\"admin\"}" \
    -H "Content-Type: application/json")
  t=$(echo "$r" | jq -r ".token")
  if [[ -n "$t" && "$t" != "null" ]]; then
    curl -s -o /dev/null -X PUT "$0/api/order/menu" -H "Content-Type: application/json" \
      -d "{\"title\":\"Sim Supreme\",\"description\":\"Simulated pie: pepperoni, mushrooms, olives, roasted garlic, basil, mozzarella, tomato sauce, oregano, red peppers, and parmesan — generated by simulate-dashboard-traffic.sh\",\"image\":\"sim-pizza-$(date +%s).png\",\"price\":0.049}" \
      -H "Authorization: Bearer $t"
    curl -s -o /dev/null "$0/api/user?page=1&limit=5&name=*" -H "Authorization: Bearer $t"
    curl -s -o /dev/null "$0/api/user/me" -H "Authorization: Bearer $t"
  fi
  sleep 45
done' "$HOST"

# --- Franchisee: login → list franchises + my franchises JSON ---
start bash -c 'while true; do
  r=$(curl -s -X PUT "$0/api/auth" \
    -d "{\"email\":\"f@jwt.com\",\"password\":\"franchisee\"}" \
    -H "Content-Type: application/json")
  t=$(echo "$r" | jq -r ".token")
  if [[ -n "$t" && "$t" != "null" ]]; then
    curl -s -o /dev/null "$0/api/franchise?page=0&limit=10&name=*"
    uid=$(echo "$r" | jq -r ".user.id")
    curl -s -o /dev/null "$0/api/franchise/${uid}" -H "Authorization: Bearer $t"
    sleep 20
    curl -s -o /dev/null -X DELETE "$0/api/auth" -H "Authorization: Bearer $t"
  fi
  sleep 12
done' "$HOST"

# --- Diner: login → varied orders (multi-item, longer JSON) → GET orders → logout ---
start bash -c 'while true; do
  r=$(curl -s -X PUT "$0/api/auth" \
    -d "{\"email\":\"d@jwt.com\",\"password\":\"diner\"}" \
    -H "Content-Type: application/json")
  t=$(echo "$r" | jq -r ".token")
  if [[ -n "$t" && "$t" != "null" ]]; then
    curl -s -o /dev/null -X POST "$0/api/order" -H "Content-Type: application/json" \
      -d "{\"franchiseId\":1,\"storeId\":1,\"items\":[{\"menuId\":1,\"description\":\"Veggie deluxe with spinach and artichoke\",\"price\":0.051},{\"menuId\":1,\"description\":\"Side breadsticks\",\"price\":0.012}]}" \
      -H "Authorization: Bearer $t"
    curl -s -o /dev/null "$0/api/order?page=1" -H "Authorization: Bearer $t"
    curl -s -o /dev/null -X POST "$0/api/order" -H "Content-Type: application/json" \
      -d "{\"franchiseId\":1,\"storeId\":1,\"items\":[{\"menuId\":1,\"description\":\"Single classic slice\",\"price\":0.03}]}" \
      -H "Authorization: Bearer $t"
    curl -s -o /dev/null -X DELETE "$0/api/auth" -H "Authorization: Bearer $t"
  fi
  sleep 6
  sleep 10
done' "$HOST"

# --- Invalid bodies: empty POST (400 + error JSON in res) ---
start bash -c 'while true; do
  curl -s -o /dev/null -X POST "$0/api/auth" -H "Content-Type: application/json" -d "{}"
  sleep 35
done' "$HOST"

# --- Too many items → pizza failure / 500 ---
start bash -c 'while true; do
  r=$(curl -s -X PUT "$0/api/auth" \
    -d "{\"email\":\"d@jwt.com\",\"password\":\"diner\"}" \
    -H "Content-Type: application/json")
  t=$(echo "$r" | jq -r ".token")
  if [[ -z "$t" || "$t" == "null" ]]; then sleep 60; continue; fi
  items="{ \"menuId\": 1, \"description\": \"Veggie\", \"price\": 0.05 }"
  for ((i = 0; i < 21; i++)); do
    items+=", { \"menuId\": 1, \"description\": \"Veggie\", \"price\": 0.05 }"
  done
  code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$0/api/order" -H "Content-Type: application/json" \
    -d "{\"franchiseId\": 1, \"storeId\":1, \"items\":[$items]}" \
    -H "Authorization: Bearer $t")
  echo "too-many-items order HTTP $code"
  sleep 2
  curl -s -o /dev/null -X DELETE "$0/api/auth" -H "Authorization: Bearer $t"
  sleep 50
done' "$HOST"

echo "==> Started ${#PIDS[@]} background loops (PIDs: ${PIDS[*]})"
wait
